[tool.poetry]
name = "Quote-Finder"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = "^1.7.2"
aiohttp = "^3.7.4"
async-timeout = "^3.0.1"
attrs = "^20.3.0"
autopep8 = "^1.5.6"
certifi = "^2020.12.5"
chardet = "^4.0.0"
et-xmlfile = "^1.0.1"
flake8 = "^3.9.0"
idna = "^3.1"
importlib-metadata = "^3.10.0"
jdcal = "^1.4.1"
lockfile = "^0.12.2"
mccabe = "^0.6.1"
multidict = "^5.1.0"
openpyxl = "^3.0.7"
pip = "^21.0.1"
pycodestyle = "^2.7.0"
pyflakes = "^2.3.1"
python-dateutil = "^2.8.1"
python-dotenv = "^0.16.0"
pytz = "^2021.1"
six = "^1.15.0"
toml = "^0.10.2"
typing-extensions = "^3.7.4"
wheel = "^0.36.2"
yarl = "^1.6.3"
zipp = "^3.4.1"
click = "^7.1.2"
waitress = "^2.0.0"
Flask = "^2.0.1"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
