"""Add chapter_count to fics table

Revision ID: 721318ea70fd
Revises: b02c3b0ac481
Create Date: 2026-06-23 04:11:21.172321

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "721318ea70fd"
down_revision: Union[str, Sequence[str], None] = "b02c3b0ac481"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fics",
        sa.Column("chapter_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fics", "chapter_count")
    # ### end Alembic commands ###
