"""Add composite index for paragraph bulk retrieval

Revision ID: b02c3b0ac481
Revises: 468cba96ea4b
Create Date: 2026-06-23 04:07:56.201416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02c3b0ac481'
down_revision: Union[str, Sequence[str], None] = '468cba96ea4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_paragraphs_chapter_para_num', 'paragraphs', ['chapter_id', 'paragraph_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paragraphs_chapter_para_num', table_name='paragraphs')
    # ### end Alembic commands ###
