"""add jobs table

Revision ID: c49ea3652078
Revises: 721318ea70fd
Create Date: 2026-06-23 04:38:36.177264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c49ea3652078"
down_revision: Union[str, Sequence[str], None] = "721318ea70fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("fic_id", sa.String(length=36), nullable=True),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_stage", sa.String(length=100), nullable=True),
        sa.Column("progress_current", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("failure_stage", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("target_url", sa.String(), nullable=True),
        sa.Column("guild_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["fic_id"], ["fics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(
        op.f("search_lines_normalized_text_trgm_idx"),
        table_name="paragraphs",
        postgresql_ops={"normalized_text": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("search_lines_normalized_text_trgm_idx"),
        "paragraphs",
        ["normalized_text"],
        unique=False,
        postgresql_ops={"normalized_text": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_table("jobs")
    # ### end Alembic commands ###
