"""Add many-to-many FicGuild association

Revision ID: dbf7f136ed15
Revises: f86293e4dd13
Create Date: 2026-06-23 03:15:51.937825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf7f136ed15'
down_revision: Union[str, Sequence[str], None] = 'f86293e4dd13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fic_guilds',
    sa.Column('fic_id', sa.String(length=32), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fic_id', 'guild_id')
    )
    op.drop_index(op.f('ix_fics_guild_id'), table_name='fics')
    op.create_foreign_key(None, 'fics', 'fic_versions', ['active_version_id'], ['id'], use_alter=True)
    op.drop_column('fics', 'guild_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fics', sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fics', type_='foreignkey')
    op.create_index(op.f('ix_fics_guild_id'), 'fics', ['guild_id'], unique=False)
    op.drop_table('fic_guilds')
    # ### end Alembic commands ###
