"""Initial migration

Revision ID: f86293e4dd13
Revises:
Create Date: 2026-06-23 03:11:22.081350

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f86293e4dd13"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fics",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_story_id", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("active_version_id", sa.String(length=32), nullable=True),
        sa.Column("auto_refresh_enabled", sa.Boolean(), nullable=False),
        sa.Column("refresh_interval_hours", sa.Integer(), nullable=True),
        sa.Column("next_refresh_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_refresh_status", sa.String(length=50), nullable=True),
        sa.Column("last_refresh_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_version_id"], ["fic_versions.id"], use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fics_guild_id"), "fics", ["guild_id"], unique=False)
    op.create_index(
        op.f("ix_fics_source_story_id"), "fics", ["source_story_id"], unique=False
    )
    op.create_table(
        "fic_versions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("fic_id", sa.String(length=32), nullable=False),
        sa.Column("epub_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("chapter_count", sa.Integer(), nullable=False),
        sa.Column("paragraph_count", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["fic_id"], ["fics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fic_versions_fic_id"), "fic_versions", ["fic_id"], unique=False
    )
    op.create_table(
        "chapters",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("fic_id", sa.String(length=32), nullable=False),
        sa.Column("version_id", sa.String(length=32), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("chapter_title", sa.String(length=255), nullable=True),
        sa.Column("source_document_path", sa.String(length=255), nullable=False),
        sa.Column("chapter_hash", sa.String(length=64), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["version_id"], ["fic_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chapters_fic_id"), "chapters", ["fic_id"], unique=False)
    op.create_index(
        op.f("ix_chapters_version_id"), "chapters", ["version_id"], unique=False
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("fic_id", sa.String(length=32), nullable=False),
        sa.Column("version_id", sa.String(length=32), nullable=False),
        sa.Column("chapter_id", sa.String(length=32), nullable=False),
        sa.Column("chunk_number", sa.Integer(), nullable=False),
        sa.Column("start_paragraph", sa.Integer(), nullable=False),
        sa.Column("end_paragraph", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chunks_chapter_id"), "chunks", ["chapter_id"], unique=False
    )
    op.create_index(op.f("ix_chunks_fic_id"), "chunks", ["fic_id"], unique=False)
    op.create_index(
        op.f("ix_chunks_version_id"), "chunks", ["version_id"], unique=False
    )
    op.create_table(
        "paragraphs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("fic_id", sa.String(length=32), nullable=False),
        sa.Column("version_id", sa.String(length=32), nullable=False),
        sa.Column("chapter_id", sa.String(length=32), nullable=False),
        sa.Column("paragraph_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paragraphs_chapter_id"), "paragraphs", ["chapter_id"], unique=False
    )
    op.create_index(
        op.f("ix_paragraphs_fic_id"), "paragraphs", ["fic_id"], unique=False
    )
    op.create_index(
        op.f("ix_paragraphs_version_id"), "paragraphs", ["version_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_paragraphs_version_id"), table_name="paragraphs")
    op.drop_index(op.f("ix_paragraphs_fic_id"), table_name="paragraphs")
    op.drop_index(op.f("ix_paragraphs_chapter_id"), table_name="paragraphs")
    op.drop_table("paragraphs")
    op.drop_index(op.f("ix_chunks_version_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_fic_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_chapter_id"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_chapters_version_id"), table_name="chapters")
    op.drop_index(op.f("ix_chapters_fic_id"), table_name="chapters")
    op.drop_table("chapters")
    op.drop_index(op.f("ix_fic_versions_fic_id"), table_name="fic_versions")
    op.drop_table("fic_versions")
    op.drop_index(op.f("ix_fics_source_story_id"), table_name="fics")
    op.drop_index(op.f("ix_fics_guild_id"), table_name="fics")
    op.drop_table("fics")
    # ### end Alembic commands ###
